### PR TITLE
added Silly wordlist, linting fixes in contributing.md

### PR DESCRIPTION
**Pull request by thomasrayner**
Adding this word list adds a choice for some simple, "silly" words with no other theme.

### CODE REVIEW

**Comment by thomasrayner** [comment]
I want @adilio to review this, but he wasn't a collaborator yet... so that's why this is sitting open with no review pending etc.

**Review by vexx32 — APPROVED** [review]
Looks good! 💖

**Comment by adilio** [comment]
Looks good to me, and I appreciate the inclusion! Love you both! ❤️

**Review by adilio — COMMENTED** [review]
LGTM!

**Pull request merged**
